### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by feelancer21** [feelancer21/feelancer#4]
Probably because of `value+shift <0`

```
/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/runner.py:45: SAWarning: Object of type <DBLnRun> not in session, add operation along 'DBLnNode.runs' will not proceed
  db_session.commit()
Traceback (most recent call last):
  File "/appexec/venv/feelancer/bin/feelancer-cli", line 8, in <module>
    sys.exit(app())
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/cli.py", line 10, in app
    Pid(session)
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/data.py", line 359, in __init__
    self.peer_controller_map = self._peer_controller_map()
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/data.py", line 440, in _peer_controller_map
    peer_controller_map[pub_key] = PeerController.from_data(
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/controller.py", line 178, in from_data
    controller(*call_args)
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/controller.py", line 198, in __call__
    self._set_controll_variable(channel_collection, feelevel_controller)
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/controller.py", line 227, in _set_controll_variable
    self.ewma_pid.set_control_variable_last(control_variable_new)
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/ewma_pid.py", line 211, in set_control_variable_last
    self._last_control_factor = self.value_to_factor(control_variable_last)
  File "/appexec/venv/feelancer/lib/python3.9/site-packages/feelancer/tasks/pid/ewma_pid.py", line 187, in value_to_factor
    return log(value + self.shift)
ValueError: math domain error
```

**Comment by feelancer21** [comment]
closed because of #8
